### ISSUE TITLE
Plerase add a feature to rotate the camera

### ISSUE THREAD

**Issue by HelgeKeck** [Lillifee/raspiCam#13]
Please make it possible to rotate the camera

**Comment by Lillifee** [comment]
Hey Helge, thanks for your feedback!
I created a new release with the rotation setting. I add the slider to the camera section (other).
![image](https://user-images.githubusercontent.com/23337626/147383996-107bdbb8-ac14-48c7-9687-541eb2962743.png)

I'm interested in how do you use the app? Do you use it for timelapse photos or videos? 
I saw your timelapse projects. https://github.com/HelgeKeck/uberlapse
Really nice, I have to try it out someday.

**Comment by HelgeKeck** [comment]
wow, thats quick. thank you. 

Could you also made the settings persistent please? That would be super nice. So i dont need to set it manually to the last settings.

Im using this to find the perfect camera settings, your interface makes it really easy, i like it. 

i needed the rotation feature bc my camera is mounted sidewards bc my camera cable is only 3 cm long

![20211225_064506](https://user-images.githubusercontent.com/13624572/147384636-c3f5b75a-2970-405a-9971-f2662cfaa05d.jpg)

![20211225_064534](https://user-images.githubusercontent.com/13624572/147384638-41ea6868-d90a-4b37-aad1-cb6b7aad283b.jpg)

**Comment by HelgeKeck** [comment]
i also recommended your project in the RatRig discord server, you dont get enough attention for this awesome project. Put a small screen to it and you have a nice digital camera, well done

**Comment by Lillifee** [comment]
That looks amazing ;) congrats, really nice job!
Thanks a lot for your recommendation. I appreciate that!

I put that project a little bit on hold. I was not sure if people were interested in such a simple front-end. In the beginning, I just wanted to observe the 3d printer, take some timelapse pictures from parties, etc.

I also tried a little bit around with TensorFlow. I'm not sure where this project is heading.
![image](https://user-images.githubusercontent.com/23337626/147388206-722e7824-dc6b-498f-b03c-dab2442920e4.png)

I did another release to persist the settings.
The initial idea was to create different presets for the sections, but that's a good start.

If you mess them up, you can reset them in the top right corner of each section or delete the files in the raspiCam/settings folder.
![image](https://user-images.githubusercontent.com/23337626/147387669-2e176bc0-120f-4bd2-bb62-fca6808f5de5.png)

**Comment by Lillifee** [comment]
What features would you need to capture the pictures directly from raspicam instead of copying and pasting the arguments? Would it help to capture a picture using the gpio pins?

**Comment by HelgeKeck** [comment]
As i said, i just use it to find the right settings. For my project this kind of tech/ui, a seperate web ui, isnt helpful at all, it needs to be integrated in Klipper and Mainsail (the 3d printer os) . Settings and controlling needs to be done from gcode and not a web ui. Also, nodejs has a fat ass compared to pure python :-) I try to keep it as simple as possible. But if you are looking for ways to pimprove your project then i would start in the photo gallery, sorting, ordering, fitlering, deleteing, ....... consistent thumbnail sizes, .....

**Comment by HelgeKeck** [comment]
i would also switch to ffmepg, this opens up a ton of possibilities for your project, like live youtube streaming, compressed timelapses, .......

**Comment by Lillifee** [comment]
Sounds reasonable! Thanks. Maybe i find some time in the next weeks. 😉 Have a nice holiday and a happy new year!

**Comment by HelgeKeck** [comment]
You too, and thanks again for making the changes so quick
