### ISSUE TITLE
ERROR: the system appears to be configured for the legacy camera stack

### ISSUE THREAD

**Issue by KaTOxDev** [Lillifee/raspiCam#21]
how to solve this error

![image](https://user-images.githubusercontent.com/98159417/182026834-452e33d5-83c4-46d5-8b87-616ae8d03b10.png)

**Comment by Lillifee** [comment]
Hey,

Raspberry Pi is transitioning from a legacy camera software stack (raspivid, raspistill) to an open-source stack based on libcamera. please check if your raspberry pi is up to date, and disable the legacy camera.

Run sudo raspi-config
Navigate to Interface Options and select Legacy camera and disable it.
Reboot your Raspberry Pi and try again.
Try to run one of the new camera apps like libcamera-still

Hope it helps!

**Comment by KaTOxDev** [comment]
Thanks , it work good now

**Comment by Lillifee** [comment]
Perfect 👍
