### ISSUE TITLE
Startup Photo Settings missing

### ISSUE THREAD

**Issue by GLOUPY-RnD** [Lillifee/raspiCam#31]
Hi,
After installing the new release, I started the web page and by default it is in Photo mode but the settings are missing (Timeout, Resolution, Quality, Timelapse).

I had to select video mode and switch back to photo mode in order to make them appear.

Dunno if it is normal so I'm pointing it out ^^

Cheers

**Comment by Lillifee** [comment]
Ahhhh sorry for that. By default its not set to Photo. Should be only at the first startup but i will fix it tomorrow. Thanks for reporting that issue!

**Comment by Lillifee** [comment]
This bug should be fixed in the latest version.
https://github.com/Lillifee/raspiCam/releases/tag/v1.3.5

**Comment by GLOUPY-RnD** [comment]
Hi,
I can confirm that this is fixed :)
