### ISSUE TITLE
Make settings-reset harder to use!

### ISSUE THREAD

**Issue by gns-jdaniel** [Lillifee/raspiCam#45]
It's super-easy to hit the reset button on any and all settings in the web client...could this be made more difficult to access and/or add a "reset? are you sure?" for the master reset button?

The "reset-settings" function icon looks like a "refresh" icon in other apps, which is less destructive.

**Comment by Lillifee** [comment]
I added a confirmation and changed the icon in the new release. 
Let me know if that works for you.

**Comment by gns-jdaniel** [comment]
Much better! Thank you!
