### ISSUE TITLE
Feature request : "Select all" photos

### ISSUE THREAD

**Issue by GLOUPY-RnD** [Lillifee/raspiCam#52]
Hi Lilifee,

A button for selecting all photos would be nice (or a direct "delete all" button).

![Screenshot 2023-05-17 at 18 57 26](https://github.com/Lillifee/raspiCam/assets/5571550/ed7f8267-0252-4d2a-bf17-b6c3e1bf5db0)

Side note : you can see that thumbnails does not work with png file format. Or maybe the resolution is too big ? Not that it matters to me but I'm reporting the issue if it matters for others.

![Screenshot 2023-05-17 at 19 13 38](https://github.com/Lillifee/raspiCam/assets/5571550/c45f256f-42d9-4ef5-912e-29e21f2d57cf)

**Comment by Lillifee** [comment]
Hey @GLOUPY-RnD,

I admit I haven't spent much time in the gallery, but I'll definitely look into it and see what I can do.

Regarding the PNG format, it's unfortunate that the thumb feature in libcamera-still is only available for JPG.
So far, I've only used JPG as the image format. Could you please let me know the reason behind choosing PNG over JPG? If PNG is preferred, I would need to create the thumbnail manually and possibly integrate an additional library for that purpose.

**Comment by Lillifee** [comment]
Hey @GLOUPY-RnD 

The latest release now allows to select a full day or all images on the top right.

**Comment by GLOUPY-RnD** [comment]
Working fine here, too !
Still no thumbnails, though ;)
