### ISSUE TITLE
Upgrade : Soft version

### ISSUE THREAD

**Issue by GLOUPY-RnD** [Lillifee/raspiCam#53]
Hi Lilifee,

I updated to the latest version of your soft. Well I think I did.
A version written somewhere, maybe at the bottom of the setting tab, would be a good idea in order to check that it's been updated.

Just a thought.

**Comment by Lillifee** [comment]
Hey @GLOUPY-RnD,

thanks for your feedback. I'll try to add it in the next version.

**Comment by Lillifee** [comment]
Hey @GLOUPY-RnD 

I added the verison in the application settings section and on startup.

![image](https://github.com/Lillifee/raspiCam/assets/23337626/8e6f3f5c-0ea8-49b9-9cb3-6ed3343cd811)

![image](https://github.com/Lillifee/raspiCam/assets/23337626/6f6bd7f2-ed63-4bb4-be9a-b99e28758136)
