### ISSUE TITLE
stream resolution higher than 1080p?

### ISSUE THREAD

**Issue by bb5d0** [Lillifee/raspiCam#58]
Using raspiCam with my RPI v2 Camera the maximum streaming format seems to be 1440x1080
But using a different streamer program I'm able to stream @ 1640x1232 (see [Hardware Specification](https://www.raspberrypi.com/documentation/accessories/camera.html#hardware-specification))

**Comment by Lillifee** [comment]
Hey @bb5d0,

During the implementation process, I experimented with various resolutions using my HQ camera. However, I discovered that the h264 encoder has a limitation of 1080p, as mentioned in this issue on GitHub: https://github.com/raspberrypi/libcamera-apps/issues/23

For instance, when I attempted to set the resolution to 2028x1520 using the command 
```
libcamera-vid --width 2028 --height 1520 --timeout 10000 --output /home/pi/raspiCam/photos/20230707084819.h264
ERROR: *** failed to start output streaming ***
``` 
Nevertheless, your suggested resolution of 1640x1232 worked fine and i added it to the presets. Thank you for that.

In addition, I have made adjustments to accommodate higher resolutions. Now, the maximum stream and video resolutions have been increased to 2304x1520, which is the maximum for high quality (HQ) mode. It's important to note that these resolutions are only compatible with the mjpeg codec.

You can find the changes in the latest release 2.0.9
https://github.com/Lillifee/raspiCam/releases/tag/v2.0.9

**Comment by Lillifee** [comment]
Hey @bb5d0,

Thanks for testing! I made some changes based on your feedback. Initially, I updated the video panel's appearance to match the photo/video mode in a recent release. However, considering user preferences, I reverted the changes and now both the video and photo panels are always displayed. I also increased the the maximum framerate to 120fps.

You can find the latest release here:
https://github.com/Lillifee/raspiCam/releases/tag/v2.0.10

**Comment by Lillifee** [comment]
Hey @bb5d0,

You could also consider using a different player or the mjpeg codec as alternatives.
![image](https://github.com/Lillifee/raspiCam/assets/23337626/05ce7b24-a8e6-4f85-95ea-ed8d3352bb80)

For h264 streams, you can enable stream statistics in the application settings to view the frames per second rendered. However, please note that these values should not be taken too seriously as they represent the average frames per second and may have a slight deviation.
![image](https://github.com/Lillifee/raspiCam/assets/23337626/2da4e5e8-ed0a-4811-9fc7-af0d3098dd27)

The framerate can be adjusted in the video settings resolution expander. If no specific value is set, libcamera will use the default framerate, typically set to 25 frames per second.
![image](https://github.com/Lillifee/raspiCam/assets/23337626/0918ce8f-7ae4-48e3-90c8-d2883b78f129)

When it comes to the fade in-out effect, I've already explored the settings in Chrome, but unfortunately, I couldn't determine why the stream stops when switching or minimizing the tab. I've experimented with the memory and energy saver options, as well as sifted through numerous flags available in chrome://flags/ but none of them seemed to address the issue directly. It appears that the MJPEG codec doesn't stop. Perhaps you could give it a shot and see if it helps resolve the problem.
I would require additional time to investigate the reasons behind Chrome freezing or sleeping disabled tabs, as well as explore possible solutions to prevent chrome from it.

**Comment by Lillifee** [comment]
Hey @bb5d0,

I apologize for the late response. I haven't tested streaming with a higher framerate before, so I can't provide a definitive answer. The performance depends on various factors such as resolution, bitrate, and so on. For example, when streaming at 720p and 60fps, I typically achieve around 52-55fps. However, I've noticed that the jmuxer player has some issues and drops frames every second. It's possible that manually setting the framerate could help, but if the expected framerate (60fps) doesn't match the actual stream framerate (52fps), we might encounter the opposite problem. In my experience, the broadway player handles higher framerates better.

Regarding performance, you can check the processes on your Raspberry Pi by using the top command and monitoring the CPU and memory usage.

For h264, here's an image showing the resource usage:
![image](https://github.com/Lillifee/raspiCam/assets/23337626/3ed5e376-f02a-4949-a872-5f592ce37f8a)

And for mjpeg, here's the corresponding image:
![image](https://github.com/Lillifee/raspiCam/assets/23337626/f8a6dc10-b3e0-4a61-9ab0-21668185dde4)

Most of the resources seem to be utilized by libcamera-vid, especially for mjpeg. The node process (raspicam) might consume more memory to buffer the video for a short time. Could you try running the libcamera-vid command from the command line without raspicam and observe the performance?

![image](https://github.com/Lillifee/raspiCam/assets/23337626/58a01c23-7bc0-4c86-a110-c0be39e35fd5)

But you have to replace the ```--output -``` to ```--output ./test.h264``` to record it on the hard disk.
The command should look like this for h264
```
libcamera-vid --nopreview --width 1280 --height 720 --framerate 25 --bitrate 6000000 --codec H264 --timeout 0 --profile baseline --inline --output ./test.h264
```
or for mjpeg
```
libcamera-vid --nopreview --width 1280 --height 720 --framerate 25 --bitrate 6000000 --codec MJPEG --timeout 0 --profile baseline --inline --output ./test.mjpeg
```

Additionally, please check if there are any warnings in the output related to client connection problems. Here's an example:
![image](https://github.com/Lillifee/raspiCam/assets/23337626/c2058815-6cdd-4da8-8bff-8975eb2792a8)

From what I've observed, the camera streamer appears to be using WebRTC. Although I initially intended to investigate WebRTC further, I ended up focusing on the two web players (jmuxer and broadway) for now. Exploring WebRTC might be one of the next topics, but it could turn into a larger undertaking.

**Comment by Lillifee** [comment]
Hey @bb5d0 

Thanks a lot for testing! 

Regarding the framerate, i found a section (High framerate capture) in the raspberry pi documentation:
https://www.raspberrypi.com/documentation/computers/camera_software.html#high-framerate-capture

**High framerate capture:**
1. The H.264 target level must be set to 4.2 with the --level 4.2 argument.
2. Software colour denoise processing must be turned off with the --denoise cdn_off argument.
3. For rates over 100 fps, disabling the display window with the -n option would free up some additional CPU cycles to help avoid frame drops.
4. It is advisable to set force_turbo=1 in /boot/config.txt to ensure the CPU clock does not get throttled during the video capture.
5. Adjust the ISP output resolution with --width 1280 --height 720 or something even lower to achieve your framerate target.
6. On a Pi 4, you can overclock the GPU to improve performance by adding gpu_freq=550 or higher in /boot/config.txt.

```
example: libcamera-vid --level 4.2 --framerate 120 --width 1280 --height 720 --save-pts timestamp.pts -o video.264 -t 10000 --denoise cdn_off -n
```

It is possible that some arguments are missing for MJPEG. I will need to experiment with libcamera to find a solution. As you can see, I am currently using the built-in libcamera-vid with the corresponding arguments. However, I cannot do much if I continue to use libcamera.

I haven't had the chance to try camera-streamer yet, but I'm curious about the difference in CPU usage compared to the libcamera-vid version. Is it a lot for h264? I also noticed that the default settings in the camera-stremer service are set to 639x480. (https://github.com/ayufan/camera-streamer/blob/main/service/camera-streamer-raspi-v2-8MP.service)
Can you send me your camera-streamer startup settings.

**Comment by Lillifee** [comment]
Im not familiar with camera-streamer, so I decided to start with the settings provided on the control page (http://myip:8080/control). 

- However, I noticed that the refresh rate of the mjpeg stream was slightly slower compared to libcamera-vid. On the positive side, the CPU usage was really impressive. I'm still trying to figure out what the issue might be with libcamera-vid.

- Next, I attempted to use webrtc. However, I noticed that the video quality seemed compressed, and the bitrate appeared to be much lower than in libcamera-vid. Additionally, the framerate felt significantly slower.

- I'm curious about how to access the video stream. When I open it using a browser or VLC player using the URL http://myip:8080/video, I experience a delay of a few seconds, and the video settings are the same as in webrtc (compressed and low frame rate).

Do i miss something here?
Hope i find time to test a little bit more....

**Comment by Lillifee** [comment]
Hey @bb5d0 ,

Regarding the MJPEG issue, I have created a report on the libcamera-apps page. Unfortunately, libcamera-vid currently relies on a software JPEG encoder (libjpeg/libjpeg-turbo), and they don't have any specific plans to implement hardware JPEG encoding. This limitation prevents me from making significant changes without switching to another library.

You can find the issue I created at this link: [GitHub Issue Link](https://github.com/raspberrypi/libcamera-apps/issues/539).

I apologize for the confusion earlier when mentioning "refresh rate." I was actually referring to the frames per second (FPS). I noticed that with the camera-streamer, the FPS felt like it was around 10, regardless of whether I used the MJPEG or H264 stream. It's possible that I made a mistake in my configuration, but regardless, I haven't been able to achieve the same level of performance with libcamera-apps.

However, I will close this issue since it was related to the stream resolution. Let's create additional issues to address specific problems more effectively.
